[package]
name = "RedNoise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sdl2 = { version = "0.35.2" }
sdl2-sys = { version = "0.35.2" }

[build-dependencies]
cc = "1.0.83"
